### PR TITLE
We're all haxorz here. Have my fixes

### PR DESCRIPTION
**Pull request by SilverCory**
Hacktoberfest is here so I'm being kind.

### CODE REVIEW

**Comment by SteveTheDog** [comment]
alex is a stupid nigger everyone type that

**Comment by SteveTheDog** [comment]
oh and DDOX ATTACK !!!!! INABATE PLUGIN DDOX MEGA SPOOF AMP DDOX !

**Comment by ducc** [comment]
cory babe im pretty sure it doesnt start counting till october

**Comment by SilverCory** [comment]
I realised now hush. XD 
On 29 Sep 2016 12:34 am, Joe Burnard notifications@github.com wrote:cory babe im pretty sure it doesnt start counting till october

**Pull request closed without merging**
